version: "3"

services:
    bot:
        build: .
        restart: unless-stopped

        environment:
            - NODE_ENV=production

        volumes:
            - ./config:/app/config

    db:
        image: mongo
        restart: unless-stopped

        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=passwd
            - MONGO_INITDB_DB=mongobin

        volumes:
            - ./database:/data/db

